galaxy_info:
  author: mosufy
  description: Update kernel-devel
  company: mosufy

  license: MIT

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - all

  galaxy_tags: []

dependencies: []