---
# Only required for development webserver

- name: Group install development tools
  command: yum -y groupinstall 'Development tools'

- name: Install zlib development tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - zlib
  - zlib-devel

- name: Install PHP70 Development tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - php70w-pecl-xdebug
  - php70w-devel
  when: php_version == 70

- name: Install PHP56 Development tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - php56w-pecl-xdebug
  - php56w-devel
  when: php_version == 56

#- name: Install PHP Development tools
#  yum:
#    name: "{{ item }}"
#    state: present
#  with_items:
#  - php-pear-PhpDocumentor
#  - php-phpunit-PHPUnit
#
#- include: dev-apigen.yml