---
# Install vbox guests addition

- name: Update kernel for vbox guests additions
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
    - kernel-devel
  notify:
    - reboot webserver