galaxy_info:
  author: mosufy
  description: Install Elasticsearch
  company: mosufy

  license: MIT

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags: []

dependencies: []