---
- name: Install LAMP with PHP70
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - httpd
  - mod_ssl
  - php70w
  - php70w-mcrypt
  - php70w-tidy
  - php70w-mysql
  - php70w-gd
  - php70w-imap
  - php70w-mbstring
  - php70w-odbc
  - php70w-pear
  - php70w-intl
  - php70w-soap
  - php70w-xml
  - php70w-xmlrpc
  - php70w-pecl-apcu
  - php70w-pecl-imagick
  - php70w-fpm