---
- name: Remove MariaDB
  yum:
    name: mariadb-libs*
    state: absent

- name: Install Percona yum repository
  yum:
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
    state: present

- name: Install Percona Client
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - Percona-Server-client-57
  - Percona-Server-shared-57

- name: Install Percona Server
  yum:
    name: Percona-Server-server-57
    state: present

- name: Create mysql log directory
  file:
    path: /var/log/mysql
    state: directory
    mode: 0755
    owner: mysql
    group: mysql

- name: Create percona mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - restart mysql